### ISSUE TITLE
composed-task-arguments and composed-task-properties options are not working

### ISSUE THREAD

**Issue by djgeary** [spring-cloud-task-app-starters/composed-task-runner#10]
We have multiple use cases where we need to pass arguments and properties to the child tasks in a composed task when it is launched (eg we have composed tasks where some properties are not set at create time but at launch time, or we need to set deployment (kubernetes) properties at launch time.

I was unable to get this working with the 1.0.0.RELEASE version of composed-task-runner, so I had a look at the code and identified a few issues, made changes locally and got it working.

The main issue seems to be there are two instances of `ComposedTaskProperties` created - one in `StepBeanDefinitionRegistrar.composedTaskProperties()` and the other presumably due to `@EnableConfigurationProperties(ComposedTaskProperties.class)` in `ComposedTaskRunnerConfiguration`. The second contains the correct ComposedTaskProperties and ComposedTaskArguments values, but the first is used to configure these on `TaskLauncherTasklet` and it contains null values so these don't get set.

I made the following changes to get it working:

`StepBeanDefinitionRegistrar.registerBeanDefinitions()`

Added the missing line:
`builder.addPropertyValue("arguments", properties.getComposedTaskArguments());`

`StepBeanDefinitionRegistrar.composedTaskProperties()`

changed `properties.setComposedTaskArguments(this.env.getProperty("composedTaskArguments"));`
to `properties.setComposedTaskArguments(this.env.getProperty("composed-task-arguments"));`
changed `properties.setComposedTaskProperties("composedTaskProperties")`   (`"composedTaskProperties"` presumably meant to be `this.env.getProperty("composedTaskProperties"))`
to `properties.setComposedTaskProperties(this.env.getProperty("composed-task-properties"));`

With these changes I was able to get the properties and arguments passed through although I think it would be worth clarifying the format of the strings passed to these properties and provide some examples of shell and rest task launch commands using this functionality. 

In particular the command strings can get very long quickly.

As an example I have a test batch job task registered as sample-batch-task with a property samplebatchtask.item-count (controls the items count in the reader to vary the length of the job)
So I have defined a test composed task like this:

`task create test-compose-samplebatchtask --definition "samplebatchtask1: sample-batch-task --samplebatchtask.item-count=4 && samplebatchtask2: sample-batch-task --samplebatchtask.item-count=2"`

Now to override the item count property in the first task (using the modified code above) I have to use this command:

`task launch test-compose-samplebatchtask --properties "app.composed-task-runner.composed-task-properties=app.test-compose-samplebatchtask-samplebatchtask1.app.sample-batch-task.samplebatchtask.item-count=2,app.composed-task-runner.composed-task-arguments=c=d" --arguments "random=10"`

ie to override this property I need 

`app.test-compose-samplebatchtask-samplebatchtask1.app.sample-batch-task.samplebatchtask.item-count=2`

which includes ‘app’ twice and the generated task name test-compose-samplebatchtask-samplebatchtask1 - is this what’s intended here? 
It might be better not to have to include the generated child task name? 

Also I’m having problems finding the correct quote mechanism to pass multiple properties and arguments in the launch command eg` app.composed-task-runner.composed-task-arguments='c=d,a=b' `doesn’t work.

Again some documentation on this would be useful.

Finally (this might be better as a separate issue) we have a few scenarios where we want to pass the same properties to all tasks in a composed job eg 
a deployment property such as `app.my-task.spring.cloud.deployer.kubernetes.hostNetwork=true`
or in the case where all the tasks are preforming operations against the same target datasource, each of the individual tasks has properties `target.datasource.url` etc and we want to be able to set that once for the composed task.

For these cases some sort of wildcard would be useful though not sure how this works with the two appearances of 'app' in the key above ideally something like 
`app.*.target.datasource.url=jdbc.... `

**Comment by cppwfs** [comment]
Thank you @djgeary for a comprehensive breakdown on issues you found while working on ComposedTaskRunner.  I'm breaking down this issue into multiple smaller issues so that they can be prioritized on the backlog.

* Properties not getting to the TaskLauncherTasklet: https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/11
* Simplifying property prefix: https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/12
* Set global property for all tasks in Composed Task: https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/13
* Using Arguments and properties at CTR launch time: https://github.com/spring-cloud/spring-cloud-dataflow/issues/1503  & https://github.com/spring-cloud/spring-cloud-dataflow/issues/1504
