### ISSUE TITLE
Standardize child task properties on CTR to be like SCDF

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud-task-app-starters/composed-task-runner#12]
As discussed here : https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/10

Since task 
task create test-compose-samplebatchtask --definition "samplebatchtask1: sample-batch-task --samplebatchtask.item-count=4 && samplebatchtask2: sample-batch-task --samplebatchtask.item-count=2"

In order to override item-count at launch time it requires the following line:
app.test-compose-samplebatchtask-samplebatchtask1.app.sample-batch-task.samplebatchtask.item-count=2

Note there are 3 components to it:
* The child task definition ie. `app.test-compose-samplebatchtask-samplebatchtask1` which is used by CTR to determine which task definition gets the property.
* The child task App i.e. `app.sample-batch-task.` which is used by dataflow to assign to the appropriate app.
* Lastly the property itself. `samplebatchtask.item-count=2`

Investigate simplifying this on the CTR if possible and if not revisit on the DataFlow project.

**Comment by cppwfs** [comment]
refer to https://github.com/spring-cloud/spring-cloud-dataflow/issues/1514 for the correct format.

**Comment by sabbyanandan** [comment]
This will be addressed in: https://github.com/spring-cloud/spring-cloud-dataflow/pull/1717.
