### ISSUE TITLE
Problems with packing

### ISSUE THREAD

**Issue by VovaViter** [spring-cloud-task-app-starters/composed-task-runner#25]
I try to run composed tasks on local-cloud-server which use SQL server.  CTR can't found dependencies for driver:
`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration': Unsatisfied dependency expressed through field 'dataSources'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Tomcat.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.tomcat.jdbc.pool.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.microsoft.sqlserver.jdbc.SQLServerDriver`
I cloned project and added dependencies in pom.xml   after that I packed new CTR and registred it:
`no main manifest attribute, in E:\SpringCloudDataFlow_demo\spring-cloud-starter-task-composedtaskrunner-1.1.1.BUILD-SNAPSHOT.jar`

**Comment by sabbyanandan** [comment]
This is already addressed in: https://github.com/spring-cloud/spring-cloud-dataflow/issues/1979
