### ISSUE TITLE
Composed task runner still runs in executing state even if child task is completed

### ISSUE THREAD

**Issue by lavanya2290** [spring-cloud-task-app-starters/composed-task-runner#37]
1. Use SCDF 1.3.0/1.4.0 release
2. Use composed task runner 1.0.0/1.1.0 RELEASE
3. Configure postgres
@echo off

pushd d:\temp
java -jar spring-cloud-dataflow-server-local-1.2.0.RELEASE.jar --spring.datasource.url=jdbc:postgresql://localhost:5432/db --spring.datasource.username=postgres --spring.datasource.password=postgres --spring.datasource.driver-class-name=org.postgresql.Driver
popd

3. Create 2 basic spring boot apps app1 and app2
4.Import spring-cloud-task-app-starters/composed-task-runner as app
4. Import app1 and app2 as app
5. Create definition: appc = app1 && app2
6. Launch task
7. Wait.

Observations:
1. app1 runs and exits
2. in batch_step_execution : it still shows executing
3. next app2 does not gets executed
4. Blocking work due to this issue.

Info:
dataflow:>app register --name composed-task-runner --type task --uri maven://org.springframework.cloud.task.app:composedtaskrunner-task:1.1.0.RELEASE
Successfully registered application 'task:composed-task-runner'

dataflow:>app register --name app1 --type task --uri maven://org.learning.springboot:app1:0.0.1-SNAPSHOT --force
Successfully registered application 'task:app1'

dataflow:>app register --name app2 --type task --uri maven://org.learning.springboot:app2:0.0.1-SNAPSHOT --force
Successfully registered application 'task:app2'

Attached logs.

[spring-cloud-dataflow-8128533042809889606.zip](https://github.com/spring-cloud-task-app-starters/composed-task-runner/files/1958641/spring-cloud-dataflow-8128533042809889606.zip)

Attached app:
[app.zip](https://github.com/spring-cloud-task-app-starters/composed-task-runner/files/1958644/app.zip)

**Comment by sabbyanandan** [comment]
Hi, @lavanya2290. Thank you for the detailed write-up. 

We have recently addressed multiple issues wrt CTR. See the [1.5 M1 release-blog](https://spring.io/blog/2018/04/20/spring-cloud-data-flow-1-5-m1-released#composed-tasks-and-nested-splits) for more details. Please try out [1.1.0.BUILD-SNAPSHOT](http://repo.spring.io/libs-snapshot/org/springframework/cloud/task/app/composedtaskrunner-task/1.1.1.BUILD-SNAPSHOT/) version of the App and share your findings. We would be able to cut a 1.1.1.RELEASE eventually.

**Comment by cppwfs** [comment]
Hello,  @lavanya2290 .   
Are the boot applications Task apps.  i.e. Do the boot applications have the `EnabledTask`  attotation?  Also do the boot apps have the postrgres dependencies specified in their pom.xml or build.gradle?

**Comment by lavanya2290** [comment]
No postgres dependencies.
Do i need to include ?
Enable Task is included

**Comment by cppwfs** [comment]
Yes.  Because the child tasks need to record their task-execution information to the db so that CTR can use that to know what to do next.

**Comment by lavanya2290** [comment]
Thanks cppwfs.
I had to configure EnableTask + spring data source url for postgres using spring data jpa.
Since it was not using the same data source as SCDF.

Appreicate your timely help and response...  👍
