### ISSUE TITLE
Cannot override dataflow-server-uri

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-task-app-starters/composed-task-runner#39]
As a user, I'm attempting to override [`dataflow-server-uri`](https://github.com/spring-cloud-task-app-starters/composed-task-runner/blob/master/spring-cloud-starter-task-composedtaskrunner/README.adoc#options), but it defaults to `localhost` always. 

It works, however, if I override it as `spring.cloud.dataflow.client.server-uri`. See discussion [here](https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5b0d2d7993dc78791c93aeb6). Investigate why there's this discrepancy between 1.1.0 and 1.1.1.

**Comment by sabbyanandan** [comment]
Another hit in SO [here](https://stackoverflow.com/questions/51292312/composed-task-using-a-different-port-than-default-9393-in-spring-cloud-data-fl).

**Comment by cppwfs** [comment]
First off lets give a little background CTR (ComposedTaskRunner) uses the DataFlowTemplate in the spring-cloud-dataflow-rest-client dependency to interface with a SCDF (Spring Cloud Data Flow).   The primary difference between CTR 1.1.0 and CTR 1.1.1 was that CTR 1.1.1 now uses the 1.5.0 release of SCDF.   In 1.5.0 spring-cloud-dataflow-rest-client adds a new auto configuration of https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java[DataFlowClientAutoConfiguration]  and with that we got the property validations for DataFlowOperations (i.e. `spring.cloud.dataflow.client.server-uri`).   With the release of 1.1.2 and 2.0.0 CTR instantiates its own DataFlowOperations which will circumvent the DataFlowClientAutoConfigurations instantiation of the DataFlowOperation bean, thus resolving the problem.

**Comment by sabbyanandan** [comment]
@cppwfs: Thank you for the research and documenting the findings!
