### ISSUE TITLE
Add support to interact with a secured SCDF server

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-task-app-starters/composed-task-runner#41]
As a user, I'd like to orchestrate a Composed Task graph against a secured SCDF server. More specifically, I'd want to interact it with basic-auth credentials.

see: spring-cloud/spring-cloud-dataflow#1972

**Acceptance:**
- To be consistent with the existing `dataflow-server-uri`, we would have to expose `dataflow-server-username` and `dataflow-server-passwords` properties for the CTR
- Supplying those credentials would allow for CTR to interact with a secured (basic-auth) SCDF server
- Document new properties (make sure they end up in the combined reference docs)
- Update test cases

**Comment by ghillert** [comment]
See also https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/42

**Comment by ilayaperumalg** [comment]
Applied the changes into 1.3.x as 8febe8f0894694da3f849e927fd7a791a0720937 and into master as 7ab9ae6b3c2abb87c87a4c9dd71843fadcd152fd
