### ISSUE TITLE
When using Boot 2.1 CTR hangs on exit when using splitter.

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud-task-app-starters/composed-task-runner#46]

**Comment by cppwfs** [comment]
This is caused by us setting the spring.cloud.task.closecontextEnabled to false by default in Task 2.0.   The workaround is to have users set spring.cloud.task.closecontextEnabled=true.    Need to set this as the default for the CTR so users won't have to do this.

**Comment by sabbyanandan** [comment]
Resolved via https://github.com/spring-cloud/spring-cloud-app-starters-maven-plugins/pull/33
