### ISSUE TITLE
Job Parameters limited to 250 characters

### ISSUE THREAD

**Issue by jsa4000** [spring-cloud-task-app-starters/composed-task-runner#88]
Hello,

I have come to a problem where I cannot store composite 'graphs' greater that 250 characters nor `composed-task-arguments`  nor `composed-task-propertires`.  The root problem is in the `string_val` column within the `BATCH_JOB_EXECUTION_PARAMS` table.

I have seen some responses over internet recommending the creation of a different table to store extra metadata for the jobs or updating this column (string_val) with higher number (>250). 

Since I am using kubernetes, I am planing to put these extra parameters into configmaps, so every deployment can pick its configuration.

Any other suggestions?

Thanks in advance

**Comment by sabbyanandan** [comment]
@jsa4000: Thanks for bringing this up. The CTR builds on Spring Batch foundation. Specifically, `BATCH_JOB_EXECUTION_PARAMS` table is associated with the core [Spring Batch schema](https://docs.spring.io/spring-batch/4.1.x/reference/html/schema-appendix.html#metaDataSchema). I'm not sure increasing the column size is a feasible option; even if we do, we may still run into similar constraint issues on larger graphs. 

While the config-map route seems like a reasonable workaround for K8s, we would have solve it for other platform users. Let's hear from the Spring Batch experts if there's anything else we can do to provide a consistent and polished experience. 

cc:/ @mminella @benas @cppwfs

**Comment by mminella** [comment]
Spring Batch, as all Spring projects, provides "sensible defaults" for all aspects of the framework.  This includes column sizes for the job repository.  You are free to increase the size of the columns as you need to suit your requirements.  There should be nothing in the code that trims a parameter to a given column size so all you should need to do is increase the value in the schema.

**Comment by sabbyanandan** [comment]
@mminella: Thanks for the clarification.

@jsa4000: I believe this recommendation should address the situation in hand, and you don't need to muck around with the configmap. 

I will close this issue for now. If you've any other feedback to share, feel free to comment on the issue, we can reopen then.

**Comment by jsa4000** [comment]
Sure, That surely responses to my answer. 

Thanks you very much
